@hostAddress = http://localhost:5119

GET {{hostAddress}}/weatherforecast/
Accept: application/json

###


GET {{hostAddress}}/api/DemoWithInclude/GetAll

###

GET {{hostAddress}}/api/DemoWithInclude/GetAllWithInclude

###

GET {{hostAddress}}/api/DemoWithInclude/GetProductsOfCategory

###
