# For more info on HTTP files go to https://aka.ms/vs/httpfile

@apiUrl = http://localhost:5083/api/Products


GET {{apiUrl}}/

###

GET {{apiUrl}}/GetAll

###

GET {{apiUrl}}/GetAll
Accept: application/xml

###

POST {{apiUrl}}
Content-Type: application/json

{
    "productId": 9,
    "name": "New Product",
    "description": "some description",
    "price": 45.75
}

###


POST {{apiUrl}}
Content-Type: application/json

{
    "productId": 10,
    "name": "New Product 10",
    "description": null,
    "price": 45.75
}

###

POST {{apiUrl}}
Content-Type: application/json

{
    "productId": 11 ,
    "name": "New Product 11",
    "price": 45.75
}

###

POST {{apiUrl}}
Content-Type: application/json

{
    "ProductId": 1000,
    "Name": "New Product 1000",
    "Description2": "some description",
    "Price": 45.75
}

###


POST {{apiUrl}}
Content-Type: application/json

{
    "ProductId": "abc",
    "Name": "New Product 1000",
    "Description": "some description",
    "Price": 45.75
}

###


POST {{apiUrl}}
Content-Type: application/json

{
    "ProductId": "500",
    "Name": "New Product 1000",
    "Description": "some description",
    "Price": 45.75
}

###


POST {{apiUrl}}
Content-Type: application/json

{
    "Name": "New Product something",
    "Description": "some description",
    "Price": 45.75
}

###

POST {{apiUrl}}
Content-Type: application/json

{
    "Description": "some description",
    "Price": 99.75
}

###
